export {
  chat,
  deleteDocument,
  getAvailableVoices,
  getParentSettings,
  getRetrievalHealth,
  getRole,
  getSessionList,
  getSessionMessages,
  getSessionUsage,
  getSubjectDocuments,
  getSubjects,
  getSubjectSessions,
  getUsageSummary,
  healthCheck,
  NetworkError,
  setRole,
  synthesizeSpeech,
  uploadDocument,
} from './client'
export type {
  ChatResponse,
  ConsistencyCheckFailure,
  ConsistencyCheckResult,
  Document,
  DocumentIngestResult,
  HealthStatus,
  MessageResponse,
  ParentSettings,
  QualitySummary,
  RetrievalHealth,
  Role,
  SessionListItem,
  SessionPreview,
  SessionUsage,
  SourceCitation,
  Subject,
  TeachingMode,
  UsageEvent,
  UsageSummary,
  VisualDirective,
  VoiceOption,
  VoiceResponse,
} from './types'
export { VoiceClient } from './voiceClient'
